vich_uploader:
    db_driver: orm
    mappings:
        user_files:
            uri_prefix: /uploads/files
            upload_destination: '%kernel.project_dir%/public/uploads/files'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options: { property: 'userDirectory' }
