controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
